# Generated by Django 3.1.7 on 2021-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='Password (warning)')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('phone', models.CharField(default=None, max_length=16, null=True, verbose_name='Mobile Phone')),
                ('recovery_email', models.EmailField(default=None, max_length=64, null=True, verbose_name='Recovery Email')),
                ('telegram', models.CharField(default=None, max_length=32, null=True, verbose_name='Telegram Nickname')),
                ('vk', models.URLField(default=None, max_length=256, null=True, verbose_name='URL to VK page')),
                ('bio', models.TextField(default=None, max_length=512, null=True, verbose_name='Bio')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('department', models.CharField(choices=[('department 1', 'department_1'), ('department_2', 'department_2')], default=None, max_length=80, null=True, verbose_name='Department')),
                ('stage', models.CharField(choices=[('stage_1', 'stage_1'), ('stage_2', 'stage_2')], default=None, max_length=16, null=True, verbose_name='Stage')),
            ],
        ),
    ]
