# Generated by Django 3.1.7 on 2021-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_problems',
            field=models.ManyToManyField(related_name='liked_users', to='questions.Problem', verbose_name='Liked problems'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_problems',
            field=models.ManyToManyField(related_name='subscribed_users', to='questions.Problem', verbose_name='Subscribed problems'),
        ),
    ]
