# Generated by Django 3.1.7 on 2021-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_problem_topics'),
        ('authorization', '0002_auto_20210322_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='interested_users', to='questions.Section', verbose_name='Interests'),
        ),
    ]
