# Generated by Django 3.1.7 on 2021-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20210330_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('nsu_mmf', 'Механико Математический Факультет'), ('nsu_gi', 'Гуманитарный институт')], default=None, max_length=80, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр')], default=None, max_length=16, null=True, verbose_name='Stage'),
        ),
    ]
