# Generated by Django 3.1.7 on 2021-04-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20210414_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=512, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='Recovery Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Telegram Nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk',
            field=models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='URL to VK page'),
        ),
    ]
