# Generated by Django 3.1.7 on 2021-04-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20210414_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='Email address'),
        ),
    ]
