# Generated by Django 3.1.7 on 2021-03-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=156, verbose_name='Title')),
                ('body', models.TextField(max_length=2048, verbose_name='Body')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Publication date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is problem solved?')),
                ('problem_type', models.CharField(choices=[('REQUEST', 'Request'), ('QUESTION', 'Question')], default=None, max_length=8, verbose_name='Problem type')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Is problem anonymous?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user', verbose_name='User')),
            ],
        ),
    ]
