# Generated by Django 3.1.7 on 2021-03-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20210322_1338'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('science_1', 'science_1'), ('science_2', 'science_2')], max_length=64, verbose_name='Science name')),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='authorization.user', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sub_1', 'sub_1'), ('sub_2', 'sub_2')], max_length=64, verbose_name='Subject name')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.science')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('section_1', 'section_1'), ('section_2', 'section_2')], max_length=64, verbose_name='Section name')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
            ],
        ),
    ]
