# Generated by Django 3.1.7 on 2021-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210322_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='questions.Section', verbose_name='Topics'),
        ),
    ]
