# Generated by Django 3.1.7 on 2021-03-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_interests'),
        ('questions', '0003_problem_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2048, verbose_name='Body')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Publication date')),
                ('anonymous', models.BooleanField()),
                ('final', models.BooleanField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='authorization.user', verbose_name='Author')),
                ('problem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.problem', verbose_name='Problem')),
            ],
        ),
    ]
