# Generated by Django 3.1.7 on 2021-04-07 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='question_problems', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
