# Generated by Django 3.1.7 on 2021-04-09 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210407_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='response',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to='questions.problem', verbose_name='Problem'),
        ),
    ]
