# Generated by Django 3.1.7 on 2021-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210409_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Science name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Section name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Subject name'),
        ),
    ]
